Don't use C99 for loop initial declarations
We don't compile with -std=c99. The rest of the code base
doesn't use this style of initial declarations so this
patch makes m4/tlog/conf_cmd.m4 generated and src/tlog-rec.c
code consistent with the code base. Another option would
be to compile the code as C99.

Addresses:
```
play_conf_cmd.c: In function ‘tlog_play_conf_cmd_load_args’:

play_conf_cmd.c:258:5: error: ‘for’ loop initial declarations are only allowed in C99 mode

     for (int i = 0; optind < argc; i++, optind++) {

     ^
```
```
tlog-rec.c: In function ‘run’:

tlog-rec.c:869:9: error: ‘for’ loop initial declarations are only allowed in C99 mode

         for (size_t i = 0; shell_argv[i] != NULL; i++) {

         ^
```