Fix signedness comparison errors
Address the type comparison errors when --enable-debug configure option is set:

play_conf_validate.c: In function ‘tlog_play_conf_validate_journal’:
play_conf_validate.c:150:27: error: comparison of integer expressions of different signedness:
 ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
             for (i = 0; i < json_object_array_length(obj); i++) {